#./doquant.sh rmdup_kidney_ko1 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Kidney_KO1/rmdup_accepted_hits.bam
#./doquant.sh rmdup_kidney_ko2 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Kidney_KO2/rmdup_accepted_hits.bam
#./doquant.sh rmdup_kidney_wt1 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Kidney_WT1/rmdup_accepted_hits.bam
#./doquant.sh rmdup_kidney_wt2 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Kidney_WT2/rmdup_accepted_hits.bam
#./doquant.sh rmdup_kidney_wt3 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Kidney_WT3/rmdup_accepted_hits.bam
#./doquant.sh rmdup_leg_ko4 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Leg_KO4/rmdup_accepted_hits.bam
#./doquant.sh rmdup_leg_ko5 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Leg_KO5/rmdup_accepted_hits.bam
#./doquant.sh rmdup_leg_wt4 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Leg_WT4/rmdup_accepted_hits.bam

#./doquant.sh rmdup_liver_ko1 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Liver_KO1/rmdup_accepted_hits.bam
#./doquant.sh rmdup_liver_ko2 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Liver_KO2/rmdup_accepted_hits.bam
#./doquant.sh rmdup_liver_wt1 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Liver_WT1/rmdup_accepted_hits.bam
#./doquant.sh rmdup_liver_wt2 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Liver_WT2/rmdup_accepted_hits.bam

#./doquant.sh rmdup_lung_ko1 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Lung_KO1/rmdup_accepted_hits.bam
#./doquant.sh rmdup_lung_ko2 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Lung_KO2/rmdup_accepted_hits.bam
#./doquant.sh rmdup_lung_ko3 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Lung_KO3/rmdup_accepted_hits.bam
#./doquant.sh rmdup_lung_wt1 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Lung_WT1/rmdup_accepted_hits.bam
#./doquant.sh rmdup_lung_wt2 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Lung_WT2/rmdup_accepted_hits.bam
#./doquant.sh rmdup_lung_wt3 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/Lung_WT3/rmdup_accepted_hits.bam
#./doquant.sh rmdup_mikeMEFs_ko1 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/mikeMEFs_KO1/rmdup_accepted_hits.bam
#./doquant.sh rmdup_mikeMEFs_ko2 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/mikeMEFs_KO2/rmdup_accepted_hits.bam
#./doquant.sh rmdup_mikeMEFs_ko3 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/mikeMEFs_KO3/rmdup_accepted_hits.bam
#./doquant.sh rmdup_mikeMEFs_wt1 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/mikeMEFs_WT1/rmdup_accepted_hits.bam
#./doquant.sh rmdup_mikeMEFs_wt2 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/mikeMEFs_WT2/rmdup_accepted_hits.bam
#./doquant.sh rmdup_mikeMEFs_wt3 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/mikeMEFs_WT3/rmdup_accepted_hits.bam

./doquant.sh rmdup_JR878 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR878/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR879 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR879/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR880 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR880/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR881 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR881/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR882 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR882/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR883 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR883/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR915 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR915/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR916 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR916/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR917 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR917/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR918 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR918/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR919 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR919/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR920 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR920/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR923 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR923/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR924 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR924/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR925 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR925/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR926 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR926/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR927 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR927/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR928 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR928/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR931 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR931/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR932 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR932/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR933 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR933/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR934 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR934/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR935 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR935/rmdup_accepted_hits.bam
./doquant.sh rmdup_JR936 /n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/JR936/rmdup_accepted_hits.bam
