Lincp21 Paper Summary Analysis Overview 
========================================================

This file contains the R code used to generate almost all of the main and supplemental summary figures. Other figure panels came from the individual reports. 


```{r options}
opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE,fig.height=4, fig.width=4,dev=c('png', 'pdf'))
```

```{r setup}
library(cummeRbund)
library(ggplot2)
library(reshape2)
alpha<-0.05 
genome<-"mm10"

all<-"/n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/diff/BROAD_ALL_3_ALL_TISSUES/"
cuff<-readCufflinks(dir=all,gtfFile="/n/rinn_data1/seq/lgoff/Projects/BrainMap/data/annotation/mm10_gencode_vM2_with_lncRNAs_and_LacZ.gtf",genome=genome)
```

```{r functions}


getRelevantSigTable<-function(cuff,alpha){
  m<-getSigTable(cuff,alpha)
  comparisons<-c("wt_brain_adultvsko_brain_adult","wt_brain_embryovsko_brain_embryo","wt_heartvsko_heart","wt_legvsko_leg","wt_livervsko_liver","wt_lungvsko_lung")
  m<-m[,comparisons]
  m<-as.data.frame(m)
  m$sum<-rowSums(m,na.rm=TRUE)
  m
}



getLogFoldChangeTable<-function(cuff){
  fpkms<-fpkmMatrix(genes(cuff))
  cols<-c("leg","liver","heart","adult_brain","embryo_brain","lung")
  foldchangeTable<-log2(fpkms[,7:12]/fpkms[,1:6]) #log2foldchange KO/WT
  colnames(foldchangeTable)<-cols
  c<-foldchangeTable
  c<-do.call(data.frame,lapply(c,function(x) replace(x,x=="-Inf",min(is.finite(x))))) #replace -Inf w NA; replace NA w column mins
  c<-do.call(data.frame,lapply(c,function(x) replace(x,x=="Inf",max(is.finite(x))))) #replace Inf w NA; replace NA with column max 
  row.names(c)<-row.names(foldchangeTable)
  c
}


modifiedHeatmap<-function(cuff,geneSetIDs){
  fpkms<-fpkmMatrix(genes(cuff))
  # annot<-annotation(genes(cuff))
  fpkms<-fpkms[which(row.names(fpkms)%in% geneSetIDs),]
  cols<-c("leg","liver","heart","adult_brain","embryo_brain","kidney","lung","MEFs")
  foldchangeTable<-log2(fpkms[,9:16]/fpkms[,1:8]) #log2foldchange KO/WT
  colnames(foldchangeTable)<-cols
  # negative = down in KO 
  # WT leg gene = 4018; KO leg gene = 3914
  # log2(KO/WT)=-0.0377378549
  c<-foldchangeTable
  c<-do.call(data.frame,lapply(c,function(x) replace(x,x=="-Inf",min(is.finite(x))))) #replace -Inf w NA; replace NA w column mins
  c<-do.call(data.frame,lapply(c,function(x) replace(x,x=="Inf",max(is.finite(x))))) #replace Inf w NA; replace NA with column max 
  row.names(c)<-row.names(foldchangeTable)
  m<-c
  
  heatRange=2
  
  m_vals <- unlist(as.list(m))[is.finite(unlist(as.list(m)))]
  m_max <- max(m_vals)
	m_min <- max(m_vals)
	range_lim <- max(c(abs(m_max), abs(m_min)))
	range_lim <- min(c(heatRange, range_lim))
	m_max <- range_lim
	m_min <- -range_lim
	m[m <  m_min] <- m_min
	m[m >  m_max] <- m_max
	m[is.na(m)] <- 0
  
	method=dist
	#m=m[hclust(method(m))$order, ] # cluster by row 
  #m=m[,hclust(method(t(m)))$order] # cluster by column
  m=m[hclust(method(m))$order ,hclust(method(t(m)))$order]#cluster by both
	
	rows=dim(m)[1]
	cols=dim(m)[2]

  melt.m=cbind(rowInd=rep(1:rows, times=cols), colInd=rep(1:cols, each=rows), melt(m))

	g=ggplot(data=melt.m)
	

		g2=g+geom_rect(aes(xmin=colInd-1,xmax=colInd,ymin=rowInd-1,ymax=rowInd, fill=value))
	

		g2=g2+scale_x_continuous(breaks=(1:cols)-0.5, labels=colnames(m))

		g2=g2+scale_y_continuous(breaks=(1:rows)-0.5, labels=rownames(m))
                               #unique(annot$gene_short_name[annot$gene_id %in% rownames(m)]))
	
    g2 <- g2 + theme(axis.ticks = element_blank()) 

	  g2=g2+theme(panel.grid.minor=element_line(colour=NA), panel.grid.major=element_line(colour=NA),panel.background=element_rect(fill=NA, colour=NA))
	
	##adjust x-axis labels
	g2=g2+theme(axis.text.x=element_text(angle=-90, hjust=0))

  
  heatscale=c(low='steelblue',mid='white',high='tomato')
  heatMidpoint=0
  legendTitle <- bquote(paste(log[2], frac("FPKM","WT",sep="")))


	if (length(heatscale) == 2){
	    g2 <- g2 + scale_fill_gradient(low=heatscale[1], high=heatscale[2], name=legendTitle)
	} else if (length(heatscale) == 3) {
	    if (is.null(heatMidpoint))
	    {
	        heatMidpoint = (max(m) + min(m)) / 2.0
	        #write(heatMidpoint, stderr())
	    }

	    g2 <- g2 + scale_fill_gradient2(low=heatscale[1], mid=heatscale[2], high=heatscale[3], midpoint=heatMidpoint, name=legendTitle)
	}
  g2
}




```

```{r figure1}
bodymapdir<-"/n/rinn_data1/users/agroff/lincNetwork/mouse/cuffnorm_shortbodymap2"
bodymap<-readCufflinks(dir=bodymapdir,gtfFile="/n/rinn_data1/seq/lgoff/Projects/BrainMap/data/annotation/mm10_gencode_vM2_with_lncRNAs_and_LacZ.gtf",genome=genome)
genesOfInterest<-c("Trp53cor1","Cdkn1a","Trp53")
genes<-getGenes(bodymap,genesOfInterest)
genesAnnot<-annotation(genes)
genesFPKMreps<-repFpkm(genes)
geneFpkms<-merge(genesAnnot,genesFPKMreps,by.x="gene_id",by.y="gene_id")
colstokeep<-c("gene_id","gene_short_name","sample_name","replicate","rep_name","fpkm")
gf<-geneFpkms[,colstokeep]
gf_wide<-dcast(gf,rep_name+sample_name~gene_short_name)
gf_wide<-gf_wide[grep("JACKS",gf_wide$rep_name,invert=TRUE),]
se <- function(x) sqrt(var(x)/length(x))
gf_mean<-aggregate(gf_wide,by=list(gf_wide$sample_name),FUN=mean)
gf_se<-aggregate(gf_wide,by=list(gf_wide$sample_name),FUN=se)
data<-gf_mean[grep("LICR",gf_mean$Group.1),]
data_se<-gf_se[which(gf_se$Group.1 %in% data$Group.1),]
limits<-aes(ymax=data$Cdkn1a+data_se$Cdkn1a,ymin=data$Cdkn1a-data_se$Cdkn1a)
plot<-ggplot(data,aes(y=Cdkn1a,x=Group.1))+geom_bar(stat="identity")+geom_errorbar(limits,width=0.2)
#pdf("p21_expression_bodymap_LICROnly.pdf")
plot+theme_bw()+theme(axis.text.x = element_text(angle = 90, hjust = 1))
#dev.off()

data_se<-gf_se[which(gf_se$Group.1 %in% data$Group.1),]
limits<-aes(ymax=data$Trp53cor1+data_se$Trp53cor1,ymin=data$Trp53cor1-data_se$Trp53cor1)
plot<-ggplot(data,aes(y=Trp53cor1,x=Group.1))+geom_bar(stat="identity")+geom_errorbar(limits,width=0.2)
#pdf("lincp21_expression_bodymap_LICROnly.pdf")
plot+theme_bw()+theme(axis.text.x = element_text(angle = 90, hjust = 1))
#dev.off()

```

```{r figure3-dendrogram}
#pdf("dendrograms.pdf")
csDendro(genes(cuff))
#'dendrogram' with 2 branches and 16 members total, at height 0.376748 
#csDendro(genes(cuff),replicates=T)
#dev.off()
```

```{r figure3_lincP21expression}
lincp21<-getGene(cuff,"Trp53cor1")
#pdf("lincp21_expression.pdf")
expressionBarplot(lincp21)+theme_bw()
#dev.off()
```

```{r figure3--alwaysSig}
sM<-getSigTable(cuff)
sM<-as.data.frame(sM)
comparisons<-c("wt_brain_adultvsko_brain_adult","wt_brain_embryovsko_brain_embryo","wt_heartvsko_heart","wt_legvsko_leg","wt_livervsko_liver","wt_lungvsko_lung")
sM<-sM[,comparisons]
sum<-rowSums(sM)
common<-sM[which(sum==8),]
commonIDs<-row.names(common)

commonGenes<-getGenes(cuff,commonIDs)
commonAnnot<-annotation(commonGenes)
alwaysSigGenes<-commonAnnot$gene_short_name
alwaysSigIDs<-commonAnnot$gene_id
#"Cdkn1a" "Glo1"   "Rnps1"  "Gm9825"

#pdf("alwaysSigFCheatmap.pdf")
modifiedHeatmap(cuff,alwaysSigIDs)
#dev.off()
```


```{r s_DE_GO}
#get aggregate universe of DE
brain_dir_adult<-"/n/rinn_data1/seq/lgoff/Projects/BrainMap/data/diffs/Trp53cor1_vs_WT_Adult"
brain_dir_embryo<-"/n/rinn_data1/seq/lgoff/Projects/BrainMap/data/diffs/Trp53cor1_vs_WT_Embryonic/"
heart_dir<-"/n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/diff/oldDiffs/Trp53cor1_E14.5_HEART/"
leg_dir<-"/n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/diff/Trp53cor1_E14.5_Leg_b0331/"
liver_dir<-"/n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/diff/Trp53cor1_E14.5_Liver_b0329/"
lung_dir<-"/n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/diff/Trp53cor1_E14.5_Lung_b0329/"

brain_embryo<-readCufflinks(dir=brain_dir_embryo,gtfFile="/n/rinn_data1/seq/lgoff/Projects/BrainMap/data/annotation/mm10_gencode_vM2_with_lncRNAs_and_LacZ.gtf",genome=genome)
brain_adult<-readCufflinks(dir=brain_dir_adult,gtfFile="/n/rinn_data1/seq/lgoff/Projects/BrainMap/data/annotation/mm10_gencode_vM2_with_lncRNAs_and_LacZ.gtf",genome=genome)
heart<-readCufflinks(dir=heart_dir,gtfFile="/n/rinn_data1/seq/lgoff/Projects/BrainMap/data/annotation/mm10_gencode_vM2_with_lncRNAs_and_LacZ.gtf",genome=genome)
leg<-readCufflinks(dir=leg_dir,gtfFile="/n/rinn_data1/seq/lgoff/Projects/BrainMap/data/annotation/mm10_gencode_vM2_with_lncRNAs_and_LacZ.gtf",genome=genome)
liver<-readCufflinks(dir=liver_dir,gtfFile="/n/rinn_data1/seq/lgoff/Projects/BrainMap/data/annotation/mm10_gencode_vM2_with_lncRNAs_and_LacZ.gtf",genome=genome)
lung<-readCufflinks(dir=lung_dir,gtfFile="/n/rinn_data1/seq/lgoff/Projects/BrainMap/data/annotation/mm10_gencode_vM2_with_lncRNAs_and_LacZ.gtf",genome=genome)

BE_sig<-getSig(brain_embryo,alpha)
BA_sig<-getSig(brain_adult,alpha)
heartsig<-getSig(heart,alpha)
legsig<-getSig(leg,alpha)
liverSig<-getSig(liver,alpha)
lungSig<-getSig(lung,alpha)

allSigGenes<-c(BA_sig,BE_sig,heartsig,legsig,liverSig,lungSig)
uniqueSig<-unique(allSigGenes)
uniqueSigGenes<-getGenes(leg,uniqueSig)
uniqueSigAnnot<-annotation(uniqueSigGenes)
#write.table(uniqueSig,file="ensembleIDS_allSigDE_fromIndividuals.tab",quote=TRUE,sep="\t",row.names=FALSE,col.names=FALSE)
#write.table(uniqueSigAnnot,file="DE_genes_aggregated_annotation.tab",quote=TRUE,sep="\t",row.names=FALSE,col.names=TRUE)
#write.table(uniqueSigAnnot$gene_short_name,file="shortNames_allSigDE_fromIndividuals.tab",quote=TRUE,sep="\t",row.names=FALSE,col.names=FALSE)


#GO DE
library(ReactomePA)
library(DOSE)
geneNames<-uniqueSigAnnot$gene_short_name
library(clusterProfiler)
require(biomaRt)

ensembl <- useMart("ENSEMBL_MART_ENSEMBL","mmusculus_gene_ensembl", 
                   host="www.ensembl.org")

#Get entrezIDs
getEntrezIDs<-function (geneNames)
{
  tmp <- getBM(attributes = c("entrezgene"), filters = "mgi_symbol", values = geneNames, mart = ensembl)
  tmp
}
sigEntrez<-getEntrezIDs(geneNames)
sigEZ<-strsplit(as.character(sigEntrez), ", ")
sigEZ<-unlist(sigEZ)
require(org.Mm.eg.db) #mapping of entrez IDs to genbank
goBP<-enrichGO(gene=sigEZ, organism="mouse",ont="BP",pvalueCutoff=0.01,readable=T)
goMF<-enrichGO(gene=sigEZ, organism="mouse",ont="MF",pvalueCutoff=0.01,readable=T)
goCC<-enrichGO(gene=sigEZ, organism="mouse",ont="CC",pvalueCutoff=0.01,readable=T)
kegg<-enrichKEGG(gene=sigEZ, organism="mouse",pvalueCutoff=.01, readable=T)
pathway<-enrichPathway(gene=sigEZ,organism="mouse",pvalueCutoff=0.01, readable=T)
pdf("bioproc_DEGO.pdf")
plot(goBP,showCategory=20) + theme(axis.text.x=element_text(angle=-90,hjust=0)) + ggtitle("Enriched BP")+theme_bw()
#dev.off()
plot(goMF,showCategory=20) + theme(axis.text.x=element_text(angle=-90,hjust=0)) + ggtitle("Enriched MF")+theme_bw()
pdf("cellcompartment_DEGO.pdf")
plot(goCC,showCategory=20) + theme(axis.text.x=element_text(angle=-90,hjust=0)) + ggtitle("Enriched CC")+theme_bw()
#dev.off()
pdf("UniverseDEGOKEGG.pdf")
plot(kegg, showCategory=20) + ggtitle("Kegg Pathways")+theme_bw()
#dev.off()
#pdf("universeDEGO_reactome.pdf")
plot(pathway,showCategory=20) + ggtitle("Reactome pathway enrichment")+theme_bw()
#dev.off()
detach("package:biomaRt")
```


```{r figure3--cdkn1aExpressionTracks}
name<-"Cdkn1a"
myGene<-getGene(leg,name)
library(GenomicFeatures)
library(Gviz)

real_chromInfo<-read.table("/n/rinn_data1/users/agroff/GITHUB/BrainMap/abbie_annotation/real_chromosomes_mm10_brainmap.chrom.info",header=TRUE)
genome<-"mm10"

mm10DB<-loadDb("/n/rinn_data1/users/agroff/GITHUB/BrainMap/analysis/mm10gencode_brainmapDB_nolacz.sqlite")

#Helper Functions
movingAverage <- function(x, n=10, centered=TRUE) {
  
  if (centered) {
    before <- floor  ((n-1)/2)
    after  <- ceiling((n-1)/2)
  } else {
    before <- n-1
    after  <- 0
  }
  
  # Track the sum and count of number of non-NA items
  s     <- rep(0, length(x))
  count <- rep(0, length(x))
  
  # Add the centered data
  new <- x
  # Add to count list wherever there isn't a
  count <- count + !is.na(new)
  # Now replace NA_s with 0_s and add to total
  new[is.na(new)] <- 0
  s <- s + new
  
  # Add the data from before
  i <- 1
  while (i <= before) {
    # This is the vector with offset values to add
    new   <- c(rep(NA, i), x[1:(length(x)-i)])
    
    count <- count + !is.na(new)
    new[is.na(new)] <- 0
    s <- s + new
    
    i <- i+1
  }
  
  # Add the data from after
  i <- 1
  while (i <= after) {
    # This is the vector with offset values to add
    new   <- c(x[(i+1):length(x)], rep(NA, i))
    
    count <- count + !is.na(new)
    new[is.na(new)] <- 0
    s <- s + new
    
    i <- i+1
  }
  
  # return sum divided by count
  s/count
}

makeBamTrack<-function(bamFile,bamName,genome=genome,chromosome,color="steelblue",window=20,ylim=c(0,300)){
  
track<-DataTrack(range=bamFile,name=bamName,genome=genome,type="h",transformation=function(x){movingAverage(x,window)},col=color,fill.histogram=color,col.histogram=color,chromosome=chromosome, ylim=ylim, lwd=1.5)
  
  return(track)
}

# Constants #########
annot<-annotation(myGene)
margin<-1000
locus<-strsplit(annot$locus,":")
locus<-unlist(locus)
chrom<-locus[[1]]
start_and_end<-strsplit(locus[[2]],"-")
start_and_end<-unlist(start_and_end)
from<-as.numeric(start_and_end[[1]])-margin
to<-as.numeric(start_and_end[[2]])+margin

genetrack<-GeneRegionTrack(mm10DB,rstarts=from,rends=to,chromosome=chrom,showId=TRUE,geneSymbol=TRUE,genome=genome,name="LincRNA Isoforms",fill="steelblue")

reps<-replicates(leg)
files<-lapply(reps$file,function(x){strsplit(x, "/")})
files<-as.data.frame(files)
samples<-(t(files[11,]))
rownames(samples)<-NULL
JRs<-samples


bamRoot<-'/n/rinn_data1/users/agroff/seq/OtherMice/Diana/lincP21/bam/'

bamFiles<-lapply(JRs,function(x){paste(bamRoot,x,"/accepted_hits.bam",sep="")})

bamNames<-reps$rep_name

specCols<-brewer.pal(3,"Paired")
colPal<-colorRampPalette(specCols)
bamColors<-colPal(length(bamFiles))


doPlot<-function(genome=genome,name,myChr,from,to,window,bamFiles,bamNames){
  #Make Tracks
  axTrack<-GenomeAxisTrack(add53 = TRUE,add35 = TRUE, labelPos = "above")
  idxTrack <- IdeogramTrack(genome = genome, chromosome = myChr)
  #BamTracks
  write("\tBamTracks",stderr())
  bamTracks<-list()
  bamOrder<-c(1:length(bamFiles))

  for (i in bamOrder){
    track<-makeBamTrack(bamFiles[[i]],bamNames[[i]],genome=genome,chromosome=myChr,color=bamColors[i],window=window)
    bamTracks<-c(bamTracks,track)
  }
  
  #Plot Tracks
  write("\tplotting...",stderr())
  # myTracks<-c(bamTracks,knownGenes)
  myTracks<-c(idxTrack,axTrack,genetrack,bamTracks)
  trackSizes<-c(1,1,4,rep(1,length(bamTracks)))

  plotTracks(myTracks,from=from,to=to,chromosome=myChr,showAxis=FALSE,background.title="black",col.title="white",col.axis="black",sizes=trackSizes,geneSymbol=TRUE)
}

#pdf("Cdkn1a_leg_tracks.pdf")
doPlot(genome=genome, name=name, myChr=chrom, from=from, to=to, window=20,bamFiles=bamFiles, bamNames=bamNames)
#dev.off()
detach("package:GenomicFeatures")
```


```{r figure4_cisSummary}
getLogFoldChangeTable<-function(cuff){
  fpkms<-fpkmMatrix(genes(cuff))
  cols<-c("leg","liver","heart","adult_brain","embryo_brain","lung")
  foldchangeTable<-log2(fpkms[,7:12]/fpkms[,1:6]) #log2foldchange KO/WT
  colnames(foldchangeTable)<-cols
  c<-foldchangeTable
  c<-do.call(data.frame,lapply(c,function(x) replace(x,x=="-Inf",min(is.finite(x))))) #replace -Inf w NA; replace NA w column mins
  c<-do.call(data.frame,lapply(c,function(x) replace(x,x=="Inf",max(is.finite(x))))) #replace Inf w NA; replace NA with column max 
  row.names(c)<-row.names(foldchangeTable)
  c
}

library(stringr)
library(plyr)

strain_name<-"Trp53cor1"

#Constants
windowSize<-4000000

getTable<-function(object){
  fullTable<-annotation(genes(object))
  write("First Split",stderr())
  firstSplit<-str_split_fixed(fullTable$locus,":",2)
  write("Second Split",stderr())
  secondSplit<-str_split_fixed(firstSplit[,2],"-",2)
  fullTable$chromosome<-firstSplit[,1]
  fullTable$start<-as.numeric(secondSplit[,1])
  fullTable$end<-as.numeric(secondSplit[,2])
  fullTable
}

#locus annotation
fullTable<-getTable(cuff)

#summary mean/se logfoldchange...
fc<-getLogFoldChangeTable(cuff)
fc$gene_id<-row.names(fc)
fullTable<-merge(fullTable,fc,by.x="gene_id",by.y="gene_id")

#reduce table 
columnstokeep<-c("gene_id","gene_short_name","chromosome","start","end","leg","liver","heart","adult_brain","embryo_brain","lung")
fullTable<-fullTable[,columnstokeep]
fullTable<-ddply(fullTable,.(gene_id),head,n=1)

myGene<-fullTable[which(fullTable$gene_short_name==strain_name),]
chromosome<-myGene$chromosome
locuslength=abs(myGene$start-myGene$end)
start<-myGene$start-(windowSize/2-locuslength/2)
end<-myGene$end+(windowSize/2-locuslength/2)

genesInRegion<-fullTable[which(fullTable$chromosome==chromosome & fullTable$start>=start & fullTable$end<=end),]

genesInRegion$start<-myGene$start-genesInRegion$start #bc lincp21 - strand 

#Sig--conglomerate from individuals -- use this!
DE<-read.table("DE_genes_aggregated_annotation.tab",header=TRUE)
DE$sig<-"yes"

data<-merge(DE,genesInRegion,by.x="gene_id",by.y="gene_id",all.y=TRUE)
data$sig[which(is.na(data$sig))]<-"NO"

colsToKeep<-c("gene_id","locus","sig","gene_short_name.y","chromosome","start","end","leg","liver","heart","adult_brain","embryo_brain","lung")
data<-data[,colsToKeep]
#colnames(data)<-c("locus","sig","gene_id","gene_short_name","seqnames","start","end","strand","chromosome")

variables<-c("gene_id","gene_short_name.y","chromosome","start","end","sig","locus")
data.melt<-melt(data,id=variables)
data.melt$value[is.na(data.melt$value)]<-0

#average log2 foldchange... 
means<-aggregate(data.melt,by=list(data.melt$gene_short_name),mean)
means<-means[,c("Group.1","value")]
colnames(means)<-c("name","mean")

#SE
se <- function(x) sqrt(var(x)/length(x))
ses<-aggregate(data.melt,by=list(data.melt$gene_short_name),se)
ses<-ses[,c("Group.1","value")]
colnames(ses)<-c("name","se")

mean_se<-merge(means,ses,by.x="name",by.y="name")
d<-merge(data,mean_se,by.x="gene_short_name.y",by.y="name")
data<-d[,c("gene_id","gene_short_name.y","chromosome","start","end","sig","se","mean")]

limits<-aes(ymin=data$mean-data$se,ymax=data$mean+data$se)

currplot<-ggplot(data,aes(start,mean,color=sig, label=gene_short_name.y))+geom_point(size=3)+scale_color_manual(values=c("black", "red"))+coord_cartesian(xlim=c(-windowSize/2, windowSize/2),ylim=c(-2.5,2.5))+geom_text(data=subset(data, sig=='yes'))+theme_bw()+geom_vline(xintercept=0, color="blue")+geom_hline(yintercept=0,color="blue")+geom_errorbar(limits,width=0.2)

#pdf("cis_region_summary_plot_may18.pdf")
currplot
#dev.off()
```

```{r sup_consistent_genes}
#which genes always change in the same direction (not sig) ? 
c<-getLogFoldChangeTable(cuff)
m<-c
up<-c
up[up>0]<-1
up[up<0]<-NA
sum<-rowSums(up)
up<-up[which(sum==6),]

down<-c
down[down<0]<-(-1)
down[down>0]<-NA
sum<-rowSums(down)
down<-down[which(sum==-6),]

downgenes<-getGenes(cuff,row.names(down))
upgenes<-getGenes(cuff,row.names(up))
upAnnot<-annotation(upgenes) 
downAnnot<-annotation(downgenes)
allAnnot<-rbind(upAnnot,downAnnot)
chr17<-allAnnot[grep('chr17',allAnnot$locus),]
consistantGenes<-c(row.names(down),row.names(up))

library(seqbias)
library(stringr)
library(plyr)

getTable<-function(ids){
  genes<-getGenes(cuff,ids)
  fullTable<-annotation(genes)
  write("First Split",stderr())
  firstSplit<-str_split_fixed(fullTable$locus,":",2)
  write("Second Split",stderr())
  secondSplit<-str_split_fixed(firstSplit[,2],"-",2)
  fullTable$chromosome<-firstSplit[,1]
  fullTable$start<-as.numeric(secondSplit[,1])
  fullTable$end<-as.numeric(secondSplit[,2])
  fullTable<-fullTable[grep("chr17",fullTable$chromosome),]
  #  fullTable$chromosome<-factor(fullTable$chromosome, levels=names(seqlengths(mm10.granges)))
  fullTable
}

dat<-getTable(consistantGenes)

#annotate which were sig in aggregate list 
DE<-read.table("DE_genes_aggregated_annotation.tab",header=TRUE)
DE$sig<-"yes"
data<-merge(DE,dat,by.x="gene_id",by.y="gene_id",all.y=TRUE)
data$sig[which(is.na(data$sig))]<-"NO"
dat<-data
rm(data)
m$gene_id<-row.names(m)
fullTable<-merge(dat,m,by.x="gene_id",by.y="gene_id")
fullTable$length<-NULL
fullTable$coverage<-NULL
fullTable$nearest_ref_id<-NULL
fullTable$class_code<-NULL
keep<-c("gene_id","sig","gene_short_name.y","chromosome","start","end","leg","liver","heart","adult_brain","embryo_brain","lung")
fullTable<-fullTable[,keep]



# melt only the logfoldchange values 
# cast molten dataframe, aggregate
variables<-c("gene_id","gene_short_name.y","sig","chromosome","start","end")
dat.melt<-melt(fullTable,id=variables)

#pdf("consistantGenes.pdf")
modifiedHeatmap(cuff,consistantGenes)
#dev.off()
```

```{r sup_consistent_Chr17}
chr17.dat.melt<-dat.melt[which(dat.melt$chromosome=="chr17"),]

#average
mean.cast<-dcast(chr17.dat.melt,gene_short_name.y~chromosome,fun.aggregate=mean)
colnames(mean.cast)<-c("name","mean")

#SE
se <- function(x) sqrt(var(x)/length(x))
se.cast<-dcast(chr17.dat.melt,gene_short_name.y~chromosome,fun.aggregate=se)
colnames(se.cast)<-c("name","se")
mean_se<-merge(se.cast,mean.cast,by.x="name",by.y="name")

dat<-merge(fullTable,mean_se,by.x="gene_short_name.y",by.y="name")
lincp21<-getGene(cuff,"Trp53cor1")
lincp21Annot<-annotation(lincp21)
lincp21_start<-29057473
centered_dat<-dat
centered_dat$start<-centered_dat$start-lincp21_start
limits<-aes(ymin=centered_dat$mean-centered_dat$se,ymax=centered_dat$mean+centered_dat$se)

#pdf("chr17_consistently_reg_genes_summary.pdf")
ggplot(centered_dat,aes(start,mean,color=sig, label=gene_short_name.y))+theme_bw()+geom_point()+geom_errorbar(limits,width=0.2)+geom_hline(yintercept=0)+geom_vline(xintercept=0)+scale_color_manual(values=c("black", "red"))+geom_text(data=subset(centered_dat, sig=='yes'))
#dev.off()
```

```{r figure5_expressionPlots}
#Cdkn1a Barplots from summary analysis 
Cdkn1a<-getGene(cuff,"Cdkn1a")
#pdf("Cdkn1a_expression.pdf")
expressionBarplot(Cdkn1a)+theme_bw()
#dev.off()

Glo1<-getGene(cuff,"Glo1")
#pdf("Glo1_expression.pdf")
expressionBarplot(Glo1)+theme_bw()
#dev.off()

```

```{r figure5_correlations}
genesOfInterest<-c("Trp53cor1","LacZ","Trp53",alwaysSigGenes)
genes<-getGenes(cuff,genesOfInterest)
genesAnnot<-annotation(genes)
genesFPKMreps<-repFpkm(genes)
geneFpkms<-merge(genesAnnot,genesFPKMreps,by.x="gene_id",by.y="gene_id")
colstokeep<-c("gene_id","gene_short_name","sample_name","replicate","rep_name","fpkm")
gf<-geneFpkms[,colstokeep]
gf_wide<-dcast(gf,rep_name+sample_name~gene_short_name)

se <- function(x) sqrt(var(x)/length(x))
gf_mean<-aggregate(gf_wide,by=list(gf_wide$sample_name),FUN=mean)
#gf_std<-aggregate(gf_wide,by=list(gf_wide$sample_name),FUN=std)
gf_se<-aggregate(gf_wide,by=list(gf_wide$sample_name),FUN=se)


#p21-lincp21
wtavg<-gf_mean[grep("wt",gf_mean$Group.1),]
wtse<-gf_se[grep("wt",gf_se$Group.1),]
limits<-aes(ymax=wtavg$Cdkn1a+wtse$Cdkn1a,ymin=wtavg$Cdkn1a-wtse$Cdkn1a)
plot<-ggplot(wtavg,aes(y=Cdkn1a,x=Trp53cor1,label=Group.1))+geom_point()+geom_errorbar(limits,width=0.2)+geom_text()
#pdf("expressioncordraft_p21lincp21.pdf")
plot
#dev.off()
#Fit 
fit<-lm(wtavg$Cdkn1a~wtavg$Trp53cor1)
summary(fit)$r.squared #0.4706





#p21-lincp21

limits<-aes(ymax=wtavg$Cdkn1a+wtse$Cdkn1a,ymin=wtavg$Cdkn1a-wtse$Cdkn1a)
plot<-ggplot(wtavg,aes(y=Cdkn1a,x=Trp53cor1,label=Group.1))+geom_point()+geom_errorbar(limits,width=0.2)+geom_text()+theme_bw()

#Fit 
fit<-lm(wtavg$Cdkn1a~wtavg$Trp53cor1) #how well is p21 predicted by lincp21? assuming linear relationship. 
#summary(fit)
#summary(fit)$r.squared #0.5284

#pdf("p21-lincp21_expression_cor.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=10,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off()


#Glo1-lincp21
fit<-lm(wtavg$Glo1~wtavg$Trp53cor1)
limits<-aes(ymax=wtavg$Glo1+wtse$Glo1,ymin=wtavg$Glo1-wtse$Glo1)
plot<-ggplot(wtavg,aes(y=Glo1,x=Trp53cor1,label=Group.1))+geom_point()+geom_errorbar(limits,width=0.2)+geom_text()+theme_bw()
#pdf("glo-lincp21_expression_cor.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=10,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off()


#Gm9825-lincp21
fit<-lm(wtavg$Gm9825~wtavg$Trp53cor1)
limits<-aes(ymax=wtavg$Gm9825+wtse$Gm9825,ymin=wtavg$Gm9825-wtse$Gm9825)
plot<-ggplot(wtavg,aes(y=Gm9825,x=Trp53cor1,label=Group.1))+geom_point()+geom_errorbar(limits,width=0.2)+geom_text()+theme_bw()
#pdf("Gm9825-lincp21_expression_cor.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=10,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off()


#Rnps1-lincp21
fit<-lm(wtavg$Rnps1~wtavg$Trp53cor1)
limits<-aes(ymax=wtavg$Rnps1+wtse$Rnps1,ymin=wtavg$Rnps1-wtse$Rnps1)
plot<-ggplot(wtavg,aes(y=Rnps1,x=Trp53cor1,label=Group.1))+geom_point()+geom_errorbar(limits,width=0.2)+geom_text()+theme_bw()
#pdf("Rnps1-lincp21_expression_cor.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=10,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off()


#Glo1-p21
fit<-lm(wtavg$Glo1~wtavg$Cdkn1a)
limits<-aes(ymax=wtavg$Glo1+wtse$Glo1,ymin=wtavg$Glo1-wtse$Glo1)
plot<-ggplot(wtavg,aes(y=Glo1,x=Cdkn1a,label=Group.1))+geom_point()+geom_errorbar(limits,width=0.2)+geom_text()+theme_bw()
#pdf("Glo1_p21_expression_cor.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=10,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off()


#p53-p21
fit<-lm(wtavg$Trp53~wtavg$Cdkn1a)
limits<-aes(ymax=wtavg$Trp53+wtse$Trp53,ymin=wtavg$Trp53-wtse$Trp53)
plot<-ggplot(wtavg,aes(y=Trp53,x=Cdkn1a,label=Group.1))+geom_point()+geom_errorbar(limits,width=0.2)+geom_text()+theme_bw()
#pdf("p53_p21_expression_cor.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=10,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off()

#p53-lncp21 
fit<-lm(wtavg$Trp53~wtavg$Trp53cor1)
limits<-aes(ymax=wtavg$Trp53+wtse$Trp53,ymin=wtavg$Trp53-wtse$Trp53)
plot<-ggplot(wtavg,aes(y=Trp53,x=Trp53cor1,label=Group.1))+geom_point()+geom_errorbar(limits,width=0.2)+geom_text()+theme_bw()
#pdf("p53_lincp21_expression_cor.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=10,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off()


```

```{r figure5_logfoldchange_correlations}
library(plyr)
fc<-getLogFoldChangeTable(cuff)
fc$gene_id<-row.names(fc)
annot<-annotation(genes(cuff))
annot<-ddply(annot,.(gene_id),head,n=1)
a<-annot[,c("gene_id","gene_short_name")]
dat<-merge(a,fc,by.x="gene_id",by.y="gene_id")
genesOfInterest<-c("Trp53cor1","LacZ","Trp53","Cdkn1a","Glo1","Rnps1","Gm9825")
fcGenesofInterest<-dat[which(dat$gene_short_name %in% genesOfInterest),]
dat<-ddply(fcGenesofInterest,.(gene_id),head,n=1)
dat.melt<-melt(dat,id.vars=c("gene_id","gene_short_name"))
dat.cast<-dcast(dat.melt,variable~gene_short_name)


genes<-getGenes(cuff,c("Trp53cor1","Cdkn1a"))
genesAnnot<-annotation(genes)
genesFPKMreps<-repFpkm(genes)
geneFpkms<-merge(genesAnnot,genesFPKMreps,by.x="gene_id",by.y="gene_id")
colstokeep<-c("gene_id","gene_short_name","sample_name","replicate","rep_name","fpkm")
gf<-geneFpkms[,colstokeep]
gf_wide<-dcast(gf,rep_name+sample_name~gene_short_name)

se <- function(x) sqrt(var(x)/length(x))
gf_mean<-aggregate(gf_wide,by=list(gf_wide$sample_name),FUN=mean)
gf_se<-aggregate(gf_wide,by=list(gf_wide$sample_name),FUN=se)

wtavg<-gf_mean[grep("wt",gf_mean$Group.1),]
lincp21_exps<-wtavg[,c("Group.1","Trp53cor1","Cdkn1a")]
lincp21_exps$Group.1<-gsub("wt_","",lincp21_exps$Group.1)
lincp21_exps$Group.1<-gsub("brain_adult","adult_brain",lincp21_exps$Group.1)
lincp21_exps$Group.1<-gsub("brain_embryo","embryo_brain",lincp21_exps$Group.1)
colnames(lincp21_exps)<-c("sample","WT_lincp21_FPKMavg","WT_Cdkn1a_FPKMavg")
dat<-merge(dat.cast,lincp21_exps,by.x="variable",by.y="sample")

#p21-lincp21
fit<-lm(dat$Cdkn1a~dat$WT_lincp21_FPKMavg)
plot<-ggplot(dat,aes(y=Cdkn1a,x=WT_lincp21_FPKMavg,label=variable))+geom_point()+geom_text()+theme_bw()
#pdf("p21-lincp21_foldchange.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=-4,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off() 


#Glo1-lincp21
fit<-lm(dat$Glo1~dat$WT_lincp21_FPKMavg)
plot<-ggplot(dat,aes(y=Glo1,x=WT_lincp21_FPKMavg,label=variable))+geom_point()+geom_text()+theme_bw()
#pdf("glo-lincp21_foldchange.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=1,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off()

#Glo1-p21
fit<-lm(dat$Glo1~dat$WT_Cdkn1a_FPKMavg)
plot<-ggplot(dat,aes(y=Glo1,x=WT_Cdkn1a_FPKMavg,label=variable))+geom_point()+geom_text()+theme_bw()
#pdf("glo-p21_foldchange.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=1,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off()


#Gm9825-lincp21
fit<-lm(dat$Gm9825~dat$WT_lincp21_FPKMavg)
plot<-ggplot(dat,aes(y=Gm9825,x=WT_lincp21_FPKMavg,label=variable))+geom_point()+geom_text()+theme_bw()
#pdf("Gm9825-lincp21_foldchange.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=2,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off()

#Rnps1-lincp21
fit<-lm(dat$Rnps1~dat$WT_lincp21_FPKMavg)
plot<-ggplot(dat,aes(y=Rnps1,x=WT_lincp21_FPKMavg,label=variable))+geom_point()+geom_text()+theme_bw()
#pdf("Rnps-lincp21_folchange.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=-1,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off()

#p53-p21
fit<-lm(dat$Trp53~dat$WT_Cdkn1a_FPKMavg)
plot<-ggplot(dat,aes(y=Trp53,x=WT_Cdkn1a_FPKMavg,label=variable))+geom_point()+geom_text()+theme_bw()
#pdf("p53-p21_foldchange.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=-4,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off() 


#p53-lincp21
fit<-lm(dat$Trp53~dat$WT_lincp21_FPKMavg)
plot<-ggplot(dat,aes(y=Trp53,x=WT_lincp21_FPKMavg,label=variable))+geom_point()+geom_text()+theme_bw()
#pdf("p53-lincp21_foldchange.pdf")
plot+stat_smooth(method="lm",se=FALSE, fullrange=TRUE)+annotate("text",x=0.5,y=-4,label=paste("r^2=",summary(fit)$r.squared,sep=""))
#dev.off() 
```




